
import sys
import os
import pandas as pd
import pdfplumber

# Add src to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

PDF_PATH = "e:/finance-ai/data/uploads/4b7fbf86-37be-4e59-bed7-fda7ec8404ef.pdf"

def debug_equity_table():
    print(f"🔍 Inspecting PDF: {PDF_PATH}")
    
    with pdfplumber.open(PDF_PATH) as pdf:
        # User said Page 6 for Equity, Page 7 for Cash Flow
        # pdfplumber is 0-indexed, so Page 6 is index 5
        
        pages_to_check = [6, 7, 8] # Indices 6, 7, 8
        
        for p_idx in pages_to_check:
            if p_idx >= len(pdf.pages): continue
            page = pdf.pages[p_idx]
            print(f"\n--- Page {p_idx + 1} ---")
            
            # debug raw text to see if digits exist
            print("RAW TEXT:")
            print(page.extract_text()[:500]) # First 500 chars

            tables = page.extract_tables()
            
            for i, table in enumerate(tables):
                df = pd.DataFrame(table)
                print(f"\n[Table {i}]")
                # Print first few rows to identify
                print(df.head(10).to_string())
                
                # Check for "Operating activities"
                if "Operating activities" in df.to_string():
                     print("✅ Found Cash Flow Table!")
                     print(df.to_string())
                     # Print explicitly the row with "generated by operating activities"
                     for idx, row in df.iterrows():
                         row_str = " ".join(str(x) for x in row.values).lower()
                         if "generated by operating activities" in row_str:
                             print(f"🎯 Target Row: {row_str}")

if __name__ == "__main__":
    import glob
    # Find any file ending with the target UUID suffix
    target_suffix = "4b7fbf86-37be-4e59-bed7-fda7ec8404ef.pdf"
    files = glob.glob(f"e:/finance-ai/data/uploads/*{target_suffix}")
    
    if files:
        PDF_PATH = files[0]
        print(f"⚠️ Using found PDF: {PDF_PATH}")
        debug_equity_table()
    else:
        print(f"❌ No PDF found ending with {target_suffix}")
