import pandas as pd
from src.analysis.query_controller import route_query
from src.visualization.chart_generator import generate_chart
import src.ai.rag_engine

# Simulating the fragmented Statement of Cash Flows from Apple Q2 2025
df_cash_flow = pd.DataFrame({
    "Cash Flow Activity": ["Cash generated by operating activities", "Net income"],
    "Six Months Ended March 29 2025 (Part 1)": ["53,", "61,"],
    "Six Months Ended March 29 2025 (Part 2)": ["887", "110"],
    "Six Months Ended March 30 2024 (Part 1)": ["62,", "57,"],
    "Six Months Ended March 30 2024 (Part 2)": ["585", "552"]
})
# We name the columns generic names except the first one to test healing
df_cash_flow.columns = ["Cash Flow Activity", "column_1", "column_2", "column_3", "column_4"]

mock_tables = [{"df": df_cash_flow, "source": "apple_q2_2025.pdf", "page": 8}]

# MOCK RAG for footnotes
def mock_retrieve(q, k=7):
    q_low = q.lower()
    res = []
    # Footnote about Ireland State Aid (Matching keywords in reconciliation)
    if any(k in q_low for k in ["ireland", "tax", "decision", "reconcile", "lower", "compare", "operating", "cash"]):
        res.append({"text": "Note 10 – Income Taxes: During the six months ended March 29, 2025, the company made a cash payment of $15.6 billion related to the Ireland State Aid Decision, which significantly impacted cash flows from operating activities."})
    return res

src.ai.rag_engine.retrieve_context = mock_retrieve

def test_full_triangulation():
    print("\n--- Testing: CFO-Grade Triangulation (Ireland State Aid Case) ---")
    q = "Compare the Net Income ($61.1B) with the Operating Cash Flow ($53.9B) for the six months ended March 29, 2025. Why is operating cash flow lower than net income?"
    
    # We pass the mock table so Layer 1 can extract figures deterministically
    ans, _ = route_query(q, mock_tables, chart_gen=generate_chart)
    print(f"\nANALYST RESPONSE:\n{ans}")
    
    # Verification
    # Expected: The LLM should see Verified Figures: Net Income: $61,110.00, Operating Cash Flow: $53,887.00
    # And it should mention Ireland/tax/15.6
    metrics_present = ("53,887" in ans or "53.9" in ans) and ("61,110" in ans or "61.1" in ans)
    footnote_present = "Ireland" in ans or "state aid" in ans or "15.6" in ans
    
    if metrics_present and footnote_present:
        print("\n✅ SUCCESS: System successfully bridged the gap between statements using deterministic extraction + footnote!")
    else:
        if not metrics_present: print("❌ Error: Metrics (53,887 or 61,110) missing from response.")
        if not footnote_present: print("❌ Error: Footnote reconciliation (Ireland/15.6B) missing.")
        print("\n❌ VERIFICATION FAILED.")

if __name__ == "__main__":
    test_full_triangulation()
