import pandas as pd
from src.analysis.query_controller import build_table_summary

# Simulate Apple's fragmented Cash Flow Statement
# "53,887" split into "53," and "887"
# Note: In real scenarios, the first column might have the label, 
# and subsequent columns have the data fragments.
df_frag = pd.DataFrame({
    "Cash Flow Activity": ["Cash generated by operating activities", "Net income"],
    "column_1": ["53,", "61,"],
    "column_2": ["887", "110"],
    "column_3": ["62,", "57,"],
    "column_4": ["585", "552"]
})

tables = [{"df": df_frag, "source": "apple_report.pdf", "page": 8}]

def test_healing():
    print("\n--- Testing: Table Healing ---")
    question = "What was the 'Net cash provided by operating activities' for the six months?"
    summary = build_table_summary(tables, question)
    print("SUMMARY OUTPUT:")
    print(summary)
    
    # Check for healed numbers
    if "53,887" in summary or ("53," in summary and "887" in summary and "," not in summary.split("53")[1].split("887")[0]):
        # The to_csv might output "53,887" or 53,887
        print("\n✅ SUCCESS: Fragmented numbers healed!")
    elif "53,887" in summary.replace('"', ''):
        print("\n✅ SUCCESS: Fragmented numbers healed (quoted)!")
    else:
        # Check if they are just merged without a comma (which is also fine for the LLM)
        if "53887" in summary:
            print("\n✅ SUCCESS: Fragmented numbers healed (comma-less)!")
        else:
            print("\n❌ FAILURE: Numbers still split or missing!")

if __name__ == "__main__":
    test_healing()
