# src/analysis/query_rewriter.py
"""
Instructed Retriever: Query Rewriter

Rewrites queries to embed constraint context directly into the embedding search.
Works with instruction_parser.py to enhance retrieval accuracy.
"""

from typing import Dict, Any, List

# ===== STATEMENT-SPECIFIC EXPANSION TERMS =====

STATEMENT_EXPANSION = {
    "Income Statement": [
        "Consolidated Statements of Operations",
        "Net Income", "Net Sales", "Total Net Sales",
        "Operating Income", "Gross Margin",
        "Statement of Operations"
    ],
    "Balance Sheet": [
        "Consolidated Balance Sheets",
        "Total Assets", "Total Liabilities",
        "Shareholders Equity", "Cash and Cash Equivalents"
    ],
    "Cash Flow Statement": [
        "Consolidated Statements of Cash Flows",
        "Cash Flows from Operating Activities",
        "Cash Generated by Operating Activities",
        "Net Cash Provided"
    ],
    "Segment Info": [
        "Segment Performance", "Revenue by Segment",
        "Operating Income by Segment", "Geographic Breakdown"
    ]
}

# Period normalization
PERIOD_EXPANSION = {
    "three_months": ["Three Months Ended", "Quarterly", "Q1 Q2 Q3 Q4"],
    "six_months": ["Six Months Ended", "Half Year", "YTD"]
}


def rewrite_query_with_instructions(
    query: str,
    instructions: Dict[str, Any]
) -> str:
    """
    Rewrite a query to embed constraint context directly.
    
    This enhances the embedding search by adding terms that will
    semantically align with the desired document chunks.
    
    Args:
        query: Original user query
        instructions: Parsed instructions from instruction_parser.parse_instructions()
        
    Returns:
        Enhanced query string for embedding
        
    Example:
        Input: "What was revenue?"
        Instructions: {period_filter: "Q2 2025", stmt_type_filter: "Income Statement"}
        Output: "What was revenue? Q2 2025 Income Statement Consolidated Statements of Operations Net Sales Total Net Sales"
    """
    expansion_terms = []
    
    # 1. Add period context
    if instructions.get("period_filter"):
        expansion_terms.append(instructions["period_filter"])
    
    if instructions.get("period_type"):
        period_type = instructions["period_type"]
        if period_type in PERIOD_EXPANSION:
            expansion_terms.extend(PERIOD_EXPANSION[period_type][:2])  # Top 2 terms
    
    # 2. Add statement-type context
    if instructions.get("stmt_type_filter"):
        stmt_type = instructions["stmt_type_filter"]
        if stmt_type in STATEMENT_EXPANSION:
            expansion_terms.extend(STATEMENT_EXPANSION[stmt_type][:3])  # Top 3 terms
    
    # 3. Add segment context
    if instructions.get("segment_filter"):
        segment = instructions["segment_filter"]
        expansion_terms.append(segment)
        # Add related terms
        if segment.lower() in ["iphone", "mac", "ipad", "wearables", "services"]:
            expansion_terms.append("Product Segment")
        elif segment.lower() in ["americas", "europe", "greater china", "japan", "asia pacific"]:
            expansion_terms.append("Geographic Segment")
    
    # 4. Add extracted keywords
    if instructions.get("keywords"):
        expansion_terms.extend(instructions["keywords"][:3])
    
    # Deduplicate while preserving order
    seen = set()
    unique_terms = []
    for term in expansion_terms:
        term_lower = term.lower()
        if term_lower not in seen and term_lower not in query.lower():
            seen.add(term_lower)
            unique_terms.append(term)
    
    # Build enhanced query
    if unique_terms:
        enhanced = f"{query} {' '.join(unique_terms)}"
        print(f"🔄 [REWRITER] Enhanced query: {query[:40]}... → +{len(unique_terms)} terms")
        return enhanced
    
    return query


def build_targeted_queries(
    query: str,
    instructions: Dict[str, Any]
) -> List[str]:
    """
    Generate multiple targeted queries for multi-query retrieval.
    
    For complex queries, generates specialized sub-queries that
    target different aspects of the question.
    
    Args:
        query: Original user query
        instructions: Parsed instructions
        
    Returns:
        List of targeted queries (original + specialized)
    """
    queries = [query]
    
    # If asking about a specific metric + segment, create a segment-focused query
    if instructions.get("segment_filter"):
        segment_query = f"{instructions['segment_filter']} {' '.join(instructions.get('keywords', []))}"
        queries.append(segment_query)
    
    # If asking about a statement type, create a statement-focused query
    if instructions.get("stmt_type_filter"):
        stmt_type = instructions["stmt_type_filter"]
        stmt_terms = STATEMENT_EXPANSION.get(stmt_type, [])
        if stmt_terms:
            stmt_query = " ".join(stmt_terms[:3])
            queries.append(stmt_query)
    
    return queries
